### ISSUE TITLE
Rename this veriable r to non general usage veriable it's giving error for global veriable r

### ISSUE THREAD

**Issue by Surendra9123** [uriyyo/async-eval#208]
https://github.com/uriyyo/async-eval/blob/d174bdfcc5ab40001ae4e3ff60391cf292997703/async_eval/async_eval.py#L80
```
    try:
      return False, await __func_wrapper__(_locals), copy_context()
    except Exception as excpz:
       return True, excpz, copy_context()
```

Good if not define veriable to no conflict

**Comment by uriyyo** [comment]
Hi @Surendra9123,

This issue should be fixed in version `0.3.1`.
