### ISSUE TITLE
NameError: name '__locals__' is not defined

### ISSUE THREAD

**Issue by Iinksafe** [uriyyo/async-eval#21]
```
Python 3.8.2 (default, Feb 26 2020, 02:56:10)
Traceback (most recent call last):
  File "<eval>", line 28, in <module>
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "<eval>", line 19, in __async_exec_func__
  File "<eval>", line 9, in __async_exec_func__
NameError: name '__locals__' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    REPL = debug.require("files/REPL @__main__")
  File "/home/runner/LinkSafePremium/files/debug.py", line 403, in require
    return getmodule(*args, **kwargs)
  File "/home/runner/LinkSafePremium/files/debug.py", line 433, in getmodule
    module = exec(f"from {regex[0]}.{regex[1]} import {regex[2]}\nreturn {regex[2]}")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/async_eval/async_eval.py", line 200, in async_eval
    exec(code_obj, _globals, _locals)
  File "<eval>", line 40, in <module>
NameError: name '__locals__' is not defined
```
![image](https://user-images.githubusercontent.com/78565096/147396367-e0371bef-0239-4543-88a6-00ba85d02e48.png)

**Comment by Iinksafe** [comment]
ignore the messy code pls ty

**Comment by Iinksafe** [comment]
just look at the exception it raises

**Comment by uriyyo** [comment]
@Iinksafe Could you please provide a minimal working example, cause I can't reproduce this issue(

**Comment by Iinksafe** [comment]
> @Iinksafe Could you please provide a minimal working example, cause I can't reproduce this issue(

Sure, wait a moment.

**Comment by Iinksafe** [comment]
![image](https://user-images.githubusercontent.com/78565096/147863781-ada95b79-1f1e-4ed1-ac4b-a56c57e7d5e2.png)
![image](https://user-images.githubusercontent.com/78565096/147863782-768648ff-4712-4135-8938-6db3470a03e4.png)
This bug seems to be fixed, but another different bug ocurred: 
![image](https://user-images.githubusercontent.com/78565096/147863793-896e636a-9830-4657-bb67-b7ce312f95b9.png)
You can test the bug at https://replit.com/@linksafe/asynceval-repro-bug.

**Comment by uriyyo** [comment]
I see, that's not a bug.

Basically, you pass custom `globals` that don't contain `BaseException`. If you want to pass some custom things inside eval you should use pass it after `globals` argument.

For instance:
```py
eval('print("Testing bug #2..."); print(geterror() or \'bug #2 passed!\')',
     globals(), {"geterror": geterror})
```

`async_eval.eval` has the same signature as builtin `__builtins__.eval` has.

**Comment by Iinksafe** [comment]
> I see, that's not a bug.
> 
> Basically, you pass custom `globals` that don't contain `BaseException`. If you want to pass some custom things inside eval you should pass it after `_globals` argument as `_locals` argument.
> 
> For instance:
> 
> ```python
> eval('print("Testing bug #2..."); print(geterror() or \'bug #2 passed!\')',
>      globals(), {"geterror": geterror})
> ```
> 
> `async_eval.eval` has the same signature as builtin `__builtins__.eval` has.

I see, thank you so much! I'll close this issue now.
